version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ml-api-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5 

  ml_api:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ml-api-service
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG-LEVEL=INFO
    depends_on:
      redis:
        condition: service_healthy 
    volumes:
      - ../app/models/ml_models:/app/app/models/ml_models:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 50s

volumes:
  redis_data: 
